WTTRPG/WTTRPG/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from create.views import *
from api.views import *


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('home_page.urls'), name="home_page"),
    path('create/',include('create.urls')),
    path('guides/',include('guides.urls')),
    path('accounts/',include('django.contrib.auth.urls')),
    path('accounts/signup', SignUpView, name="sign_up"),
    path('api/', include('api.urls'))

]

WTTRPG/api/urls.py
from django.urls import path
from . import views
from .views import *

app_name = 'api'

urlpatterns = [
    path('character/weapons', views.fetchWeapons, name='fetchWeapons'),
    path('character/levelUp', views.levelUp, name='levelup'),
    path('fetchAllWeapons', views.fetchAllWeapons, name='fetchAllWeapons'),
    path('addWeapon', views.addWeapon, name="addWeapon")

]

WTTRPG/create/urls.py
from django.urls import path
from . import views
from .views import *

app_name = 'create'

urlpatterns = [
    path('', views.create_view),
    path('homebrew/', views.homebrew_view),
    path('quickstart_create/',QSCharCreator.as_view(), name='qscc'),
    path('character_detail/<int:pk>', CharacterSheet.as_view(), name="character_sheet"),
    path('update_skills', views.update_skills, name="update_skills"),
    path('retrieve_skills', views.retrieve_skills, name="retrieve_skills"),
    path('character_list/',CharacterListView.as_view(), name="character_list"),
    path('test_packet/', views.download_testpacket, name = 'test_packet'),
    path('oneshot/', views.download_oneshot, name = 'oneshot'),
    path('user_profile/', UserProfileView.as_view(), name= 'user_profile') 
]

WTTRPG/WTTRPG/templates/Header_and_Footer.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <Meta charset="utf-8">
        <title>Gumption</title>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
        <link href="https://fonts.googleapis.com/css2?family=Lato:wght@400;700&display=swap" rel="stylesheet">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
        <style>
            body {
                font-family: 'Lato', sans-serif;
            }
    
            h1 {
                font-family: 'Lato', sans-serif;
            }

            p {
                font-family: 'Lato', sans-serif;
            }
        </style>
    </head>
    <nav class="navbar navbar-expand" style="background-color: Black;">
      <header class="container-fluid">
        <div class="text-bg-dark">
         <ul class="nav col-12 col-lg-auto me-lg-auto justify-content-center mb-md-0 me-2" style="background-color: black;">
                  <li><a href="{% url 'home_page'%}" class="nav-link link-offset-2 link-offset-3-hover link-secondary link-underline-opacity-0 link-underline-opacity-75-hover text-light ms-5 me-5">Gumption</a></li>
                  <span class="border-start"></span>
                  <div class="text-end ms-3 me-3 mt-2">
                    <li><a href="{% url 'home_page'%}" class="d-block link-offset-2 link-offset-3-hover link-secondary link-underline-dark text-light">Open Test</a></li>
                  </div>
            </header>
                <div class="col-4 d-flex justify-content-end">
                <form class="btn me-2" style="background-color: white;" role="search" id="search-button">
                  <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-search" viewBox="0 0 16 16">
                    <path d="M11.742 10.344a6.5 6.5 0 1 0-1.397 1.398h-.001q.044.06.098.115l3.85 3.85a1 1 0 0 0 1.415-1.414l-3.85-3.85a1 1 0 0 0-.115-.1zM12 6.5a5.5 5.5 0 1 1-11 0 5.5 5.5 0 0 1 11 0"/>
                  </svg>
                  <input type="text" id="search-input" style="display: none;">
                </form>
                {% if user.is_authenticated %}
                <div class="col-4 d-flex justify-content-end">
                  <div class="dropdown text-end">
                    <a href="#" class="link-body-emphasis text-decoration-light dropdown-toggle me-5" data-bs-toggle="dropdown" aria-expanded="false">
                      <img src="https://github.com/mdo.png" alt="mdo" width="32" height="32" class="rounded-circle">
                    </a>
                    <ul class="dropdown-menu text-small" style="max-width: 150px; white-space: nowrap;">
                      <li><a class="dropdown-item" href="{% url 'create:character_list'%}">Characters</a></li>
                      <li><form method="post" action="{% url 'logout' %}" class="dropdown-item">
                        {% csrf_token %}
                        <button type="submit" class="btn btn-primary btn-sm">Log Out</button>
                    </form></li>
                    </ul>
                  </div>
                {% else %}
                <div class="text-end ms-3 me-3 mt-2">
                  <a href="/accounts/login" class="d-block link-offset-2 link-offset-3-hover link-secondary link-underline-dark text-dark">Login</a>
                {% endif %}
            </div>
        </nav>
      <body class="d-flex flex-column min-vh-100" style="background-color: #f0d7a8;">
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js" integrity="sha384-BBtl+eGJRgqQAUMxJ7pMwbEyER4l1g+O15P+16Ep7Q9Q+zqX6gSbd85u4mG4QzX+" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
        <script>
          const searchButton = document.getElementById('search-button');
          const searchInput = document.getElementById('search-input');
          searchButton.addEventListener('click', function() {

              searchInput.style.display = (searchInput.style.display === 'none' || searchInput.style.display === '') ? 'block' : 'none';
      
              if (searchInput.style.display === 'block') {
                  searchInput.focus();
              }
          });
      </script>
    </body>
    {%block content%}


    {%endblock%}

   <div class="container mt-auto" style="background-color: #f0d7a8;">
        <footer class="mt-auto">
          <ul class="nav justify-content-center border-bottom border-dark pb-3 mb-3">
            <li class="nav-item"><a href="#" class="nav-link px-2 text-body-secondary">Contact Us: support@raspberryjamgames.com</a></li>
            <li class="nav-item"><a href="https://www.x.com/gumptiongame" class="nav-link px-2 text-body-secondary text-decoration-underline">X</a></li>
            <li class="nav-item"><a href="https://www.instagram.com/gumptionttrpg" class="nav-link px-2 text-body-secondary text-decoration-underline">Instagram</a></li>
            <li class="nav-item"><a href="https://www.patreon.com/GumptionTTRPG" class="nav-link px-2 text-body-secondary text-decoration-underline">Patreon</a></li>
            <li class="nav-item"><a href="https://discord.gg/Zu54fUH6uK" class="nav-link px-2 text-body-secondary">Discord</a></li>
          </ul>
          <p class="nav-item"><a href="https://www.raspberryjamgames.com/" class="nav-link-underline px-2 text-body-secondary">©Raspberry Jam</a></p>
        </footer>
      </div>
</html>

WTTRPG/WTTRPG/templates/Header_and_Footer_old.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <Meta charset="utf-8">
        <title>Gumption</title>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    </head>
    <nav class="navbar navbar-expand" style="background-color: white;">
      <header class="container-fluid">
        <div class="text-bg-dark">
            <ul class="nav col-12 col-lg-auto me-lg-auto justify-content-center mb-md-0 me-2" style="background-color: white;">
              <li><a href="{% url 'home_page'%}" class="nav-link link-offset-2 link-offset-3-hover link-secondary link-underline-opacity-0 link-underline-opacity-75-hover text-dark ms-5 me-5">Gumption</a></li>
              <span class="border-start"></span>
              <div class="text-end ms-3 me-3 mt-2">
                <li><a href="{% url 'getting_started'%}" class="d-block link-offset-2 link-offset-3-hover link-secondary link-underline-dark text-dark">Getting Started</a></li>
              </div>
          
              <div class="dropdown text-end ms-3 me-3 mt-2">
                <a href="#" class="d-block mr-3 link-offset-2 link-offset-3-hover link-secondary link-underline-dark text-dark dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
                  Guide Books
                </a>
                <ul class="dropdown-menu dropdown-menu-dark text-small">
                  <li><a class="dropdown-item" href="#">Main guide book</a></li>
                  <li><a class="dropdown-item" href="#">Adventure 1</a></li>
                </ul>
              </div>
            <div class="text-end ms-3 me-3 mt-2">
              <li><a href="" class="d-block link-offset-2 link-offset-3-hover link-secondary link-underline-dark text-dark">Marketplace</a></li>
            </div>
            </header>
                <div class="col-4 d-flex justify-content-end">
                <form class="btn me-2" style="background-color: white;" role="search" id="search-button">
                  <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-search" viewBox="0 0 16 16">
                    <path d="M11.742 10.344a6.5 6.5 0 1 0-1.397 1.398h-.001q.044.06.098.115l3.85 3.85a1 1 0 0 0 1.415-1.414l-3.85-3.85a1 1 0 0 0-.115-.1zM12 6.5a5.5 5.5 0 1 1-11 0 5.5 5.5 0 0 1 11 0"/>
                  </svg>
                  <input type="text" id="search-input" style="display: none;">
                </form>
                {% if user.is_authenticated %}
                <div class="col-4 d-flex justify-content-end">
                  <div class="dropdown text-end">
                    <a href="#" class="link-body-emphasis text-decoration-light dropdown-toggle me-5" data-bs-toggle="dropdown" aria-expanded="false">
                      <img src="https://github.com/mdo.png" alt="mdo" width="32" height="32" class="rounded-circle">
                    </a>
                    <ul class="dropdown-menu text-small" style="max-width: 150px; white-space: nowrap;">
                      <li><a class="dropdown-item" href="../create/character_list">Characters</a></li>
                      <li><a class="dropdown-item" href="#">Profile</a></li>
                      <li><a class="dropdown-item" href="#">Account</a></li>
                      <li><hr class="dropdown-divider"></li>
                      <li><form method="post" action="{% url 'logout' %}">
                        {% csrf_token %}
                        <button type="submit">logout</button>
                    </form></li>
                    </ul>
                  </div>
                {% else %}
                <div class="text-end ms-3 me-3 mt-2">
                  <a href="/accounts/login" class="d-block link-offset-2 link-offset-3-hover link-secondary link-underline-dark text-dark">Login</a>
                </div>
                  <button type="button" class="btn btn-outline-dark btn-sm me-3 text-white" style="background-color: #226150;">Sign-up</button>
                </div>
                {% endif %}
            </div>
        </nav>
      <body style="background-color: #226150;">
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js" integrity="sha384-BBtl+eGJRgqQAUMxJ7pMwbEyER4l1g+O15P+16Ep7Q9Q+zqX6gSbd85u4mG4QzX+" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
        <script>
          const searchButton = document.getElementById('search-button');
          const searchInput = document.getElementById('search-input');
          searchButton.addEventListener('click', function() {

              searchInput.style.display = (searchInput.style.display === 'none' || searchInput.style.display === '') ? 'block' : 'none';
      
              if (searchInput.style.display === 'block') {
                  searchInput.focus();
              }
          });
      </script>
    </body>
    {%block content%}


    {%endblock%}

   <div class="container">
        <footer class="py-3 my-4">
          <ul class="nav justify-content-center border-bottom pb-3 mb-3">
            <li class="nav-item"><a href="#" class="nav-link px-2 text-body-secondary">Contact Us</a></li>
            <li class="nav-item"><a href="x.com/gumptiongame" class="nav-link px-2 text-body-secondary">X</a></li>
            <li class="nav-item"><a href="instagram.com/gumptionttrpg" class="nav-link px-2 text-body-secondary">Instagram</a></li>
            <li class="nav-item"><a href="patreon.com/gumptionttrpg" class="nav-link px-2 text-body-secondary">Patreon</a></li>
          </ul>
          <p class="text-center text-body-secondary">©2025 Raspberry Jam</p>
        </footer>
      </div>
</html>