WTTRPG/WTTRPG/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from create.views import *
from api.views import *


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('home_page.urls'), name="home_page"),
    path('create/',include('create.urls')),
    path('guides/',include('guides.urls')),
    path('accounts/',include('django.contrib.auth.urls')),
    path('accounts/signup', SignUpView, name="sign_up"),
    path('api/', include('api.urls'))

]

WTTRPG/api/urls.py
from django.urls import path
from . import views
from .views import *

app_name = 'api'

urlpatterns = [
    path('character/weapons', views.fetchWeapons, name='fetchWeapons'),
    path('character/levelUp', views.levelUp, name='levelup'),
    path('fetchAllWeapons', views.fetchAllWeapons, name='fetchAllWeapons'),
    path('addWeapon', views.addWeapon, name="addWeapon")

]

WTTRPG/create/urls.py
from django.urls import path
from . import views
from .views import *

app_name = 'create'

urlpatterns = [
    path('', views.create_view),
    path('homebrew/', views.homebrew_view),
    path('quickstart_create/',QSCharCreator.as_view(), name='qscc'),
    path('character_detail/<int:pk>', CharacterSheet.as_view(), name="character_sheet"),
    path('update_skills', views.update_skills, name="update_skills"),
    path('retrieve_skills', views.retrieve_skills, name="retrieve_skills"),
    path('character_list/',CharacterListView.as_view(), name="character_list"),
    path('test_packet/', views.download_testpacket, name = 'test_packet'),
    path('oneshot/', views.download_oneshot, name = 'oneshot'),
    path('user_profile/', UserProfileView.as_view(), name= 'user_profile') 
]

WTTRPG/create/forms.py
from django import forms
from .models import *
from collections import Counter
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

#creating a form class to use in the createview so i can override the clean file method and do custom validation
class CharacterCreateForm(forms.ModelForm):
    def clean(self):
        chosenOptions = self.cleaned_data.items()
        chosenSkills = {}
        for k, v in chosenOptions:
            if k.__contains__("skill"):
                chosenSkills[k] = v
        counts = Counter(chosenSkills.values())
        result = {k: v for k , v in chosenSkills.items() if counts[v] > 1}
        if len(list(result.keys())) > 0:
            raise forms.ValidationError("Please make sure you are selecting a skill only once!")

    class Meta:
        model = Character
        fields = ['name', 'species', 'background', 'major_skill_1','major_skill_2','major_skill_3','minor_skill_1','minor_skill_2','minor_skill_3','minor_skill_4','minor_skill_5','strength','agility','intelligence','gumption','mysticism','personality','language','morals','weapon_proficiency','starting_weapon','starting_equipment','class_name']
        exclude = ['user']

class SignUpForm(UserCreationForm):
    def clean(self):
        cleaned_data = super().clean()
        pass1 = cleaned_data.get("password1")
        pass2 = cleaned_data.get("password2")
        

        if pass1 != pass2:
            raise forms.ValidationError("Passwords do not match")
        return cleaned_data

    class Meta:
        model = User
        fields = ['email','username','password1','password2']
        exclude = ['date_joined']

WTTRPG/create/views.py
from django.db.models.query import QuerySet
from django.forms import BaseModelForm
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.views.generic import FormView, CreateView, DetailView, ListView
from create.models import Character, Weapon
from .forms import *
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt
import json
from .create_settings import *
import csv
from django.contrib.auth import authenticate, login
from django.http import FileResponse
from .models import TestPacketFile
from django.contrib.auth.decorators import login_required


def bulk_DB_upload():
    with open(r'C:\Users\grntn\OneDrive\Documents\wwttrpg\WWTTRPG\WTTRPG\create\CSV_Test.csv', newline='') as csvfile:
        reader = csv.DictReader(csvfile)
        for row in reader:
           StartingEquipment.objects.create(
                name = row['name'],
                itemList = row['itemList'],
            )

#bulk_DB_upload()


# Create your views here.

def download_testpacket(request):
    uploaded_file = TestPacketFile.objects.get(pk=2)
    response = FileResponse(uploaded_file.tpFile, content_type='application/force-download')
    response['Content-Disposition'] = f'attachment; filename={uploaded_file.tpFile.name}'
    return response

def download_oneshot(request):
    uploaded_file = OneShotFile.objects.get(pk=2)
    response = FileResponse(uploaded_file.tpFile, content_type='application/force-download')
    response['Content-Disposition'] = f'attachment; filename={uploaded_file.tpFile.name}'
    return response


def create_view(request):
    return(render(request,"create/create_page.html"))

def homebrew_view(request):
    return(render(request,"create/homebrew.html"))

class CharacterListView(LoginRequiredMixin,ListView):
    model = Character
    
    #need to adjust queryset so only characters created by the logged in user are pulled

    def get_queryset(self):
        qSet = super().get_queryset()

        loggedInUser = self.request.user
        qSet = qSet.filter(user=loggedInUser)

        return qSet

class QSCharCreator(LoginRequiredMixin,CreateView):
    model = Character
    success_url = '/home_page/'
    form_class = CharacterCreateForm

    def leveling_table(self,stat,table):
        i = 0
        keys = list(table.keys())
        while i < len(keys):
            if stat == keys[i]:
                return table.get(keys[i])
            if stat > keys[i]:
                if stat < keys[i + 1]:
                    return table.get(keys[i])
                else:
                    i = i + 1
                


    def compute_stats(self,gump,str,agi,lvl):
        gump_health = {5:15,10:20,20:25,30:35,40:40,50:55,60:65,70:75,80:90,90:115,100:130}
        str_move = {5:15,15:20,30:25,45:30,60:35,75:40,90:45,100:50}
        agi_ec = {5:11,10:12,20:13,30:14,40:15,50:16,60:17,70:18,80:19,90:20,100:23}
        level_ap = {1:4,3:6,8:7,15:8,20:9}
        hp = self.leveling_table(gump,gump_health)
        mb = self.leveling_table(str,str_move)
        ec = self.leveling_table(agi,agi_ec)
        ap = self.leveling_table(lvl,level_ap)
        stats = {"hp":hp,"mb":mb,"ec":ec,"ap":ap}
        return stats


    def form_valid(self, form):
        Character = form.save(commit=False)
        Character.user = self.request.user  # Set the user field
        newInv = Inventory.objects.create()
        Character.inventory = newInv
        Character.inventory.weapons.append({'name':str(form.cleaned_data['starting_weapon'])})
        print(Character.inventory.weapons)
        Character.inventory.save()
        Character.level = 1
        stats = self.compute_stats(form.cleaned_data['gumption'],form.cleaned_data['strength'],form.cleaned_data['agility'],1)
        Character.hp = stats.get("hp")
        Character.mb = stats.get("mb")
        Character.ec = stats.get("ec")
        Character.ap = stats.get("ap")
        majSk = [form.cleaned_data['major_skill_1'],form.cleaned_data['major_skill_2'],form.cleaned_data['major_skill_3']]
        minSk = [form.cleaned_data['minor_skill_1'],form.cleaned_data['minor_skill_2'],form.cleaned_data['minor_skill_3'],form.cleaned_data['minor_skill_4'],form.cleaned_data['minor_skill_5']]
        for sk in majSk:
            conv_sk = Skills_to_ModelName.skilldic[sk]
            print(conv_sk)
            setattr(Character,conv_sk,25)
        for sk in minSk:
            conv_sk = Skills_to_ModelName.skilldic[sk]
            print(conv_sk)
            setattr(Character,conv_sk,15)
        charBackground = form.cleaned_data['background']
        bgBonuses = BackgroundBonuses.bonuses[charBackground]
        for skill, value in bgBonuses.items():
            currentValue = getattr(Character, skill)
            setattr(Character, skill, currentValue + value)
        Character.save()        
        return redirect('/create/character_detail/' + str(Character.id))  # Redirect to a success page

def SignUpView(request):
    form = SignUpForm(request.POST or None)
    if request.method == "POST":
        if form.is_valid():
            user = User.objects.create_user(form.cleaned_data['username'], form.cleaned_data['email'], 
                                           form.cleaned_data['password1'])
            login(request, user)
            return redirect('home_page')
        else:
            errors = form.errors
            for field_name, error_list in errors.items():
                for error in error_list:
                    print(f"Error in field '{field_name}': {error}")
            return render(request,"registration/create_account.html", {'form':form})
    return render(request,"registration/create_account.html", {'form':form})

class CharacterSheet(DetailView):
    model = Character

@csrf_exempt
def update_skills(request):
    #request should contain primary key for character, skill to increment, value to increment
    if request.method == 'POST':
        primary_key = request.POST.get('id')
        skill_to_update = "sk_" + request.POST.get('skill')
        increment = request.POST.get('increment')
        if primary_key and skill_to_update and increment:
            obj = Character.objects.get(id=primary_key)
            current_sk_value = getattr(obj, skill_to_update)
            new_sk_value = current_sk_value + int(increment)
            setattr(obj, skill_to_update, new_sk_value)
            obj.save()
            return JsonResponse({'status': 'success'})
        else:
            return JsonResponse({'status': 'error', 'message': 'Failed to update skills'})
    else:
        return JsonResponse({'status': 'error', 'message': 'Invalid request method'})
    

@csrf_exempt
def retrieve_skills(request):
    if request.method == 'GET':
       primary_key = request.GET.get('id')
       obj = Character.objects.get(id=primary_key)
       response_string = {
           'status':'success',
           'crushing':{'level': obj.sk_crushing, 'xp': 0},
           'shotguns':{'level': obj.sk_shotguns, 'xp': 0},
           'hand':{'level': obj.sk_hand, 'xp': 0},
           'athletics':{'level': obj.sk_athletics, 'xp': 0},
           'crafting':{'level': obj.sk_crafting, 'xp': 0},
           'slashing':{'level': obj.sk_slashing, 'xp': 0},
           'pistols':{'level': obj.sk_pistols, 'xp': 0},
           'archery':{'level': obj.sk_archery,'xp': 0},
           'ropework':{'level': obj.sk_ropework, 'xp': 0},
           'acrobatics':{'level': obj.sk_acrobatics, 'xp': 0},
           'sneak':{'level': obj.sk_sneak, 'xp': 0},
           'thievery':{'level':obj.sk_thievery, 'xp': 0},
           'intimidation':{'level':obj.sk_intimidation, 'xp': 0},
           'hunting':{'level':obj.sk_hunting, 'xp': 0},
           'animal':{'level':obj.sk_animalhandling, 'xp': 0 },
            'rifles': { 'level': obj.sk_rifles, 'xp': 0 },
            'intuition': { 'level': obj.sk_intuition , 'xp': 0 },
            'investigation': { 'level': obj.sk_investigation , 'xp': 0 },
            'gambit': { 'level':obj.sk_gambit, 'xp': 0 },
            'brewing': { 'level': obj.sk_brewing, 'xp': 0 },
            'galvanism': { 'level': obj.sk_galvanismmagic, 'xp': 0 },
            'religion': { 'level': obj.sk_religion, 'xp': 0 },
            'history': { 'level': obj.sk_history, 'xp': 0 },
            'medicine': { 'level': obj.sk_medicine, 'xp': 0 },
           'healing': { 'level': obj.sk_healingmagic, 'xp': 0 },
            'utility': { 'level': obj.sk_utilitymagic, 'xp': 0 },
            'absolution': { 'level': obj.sk_absolutionmagic, 'xp': 0 },
            'foolery': { 'level': obj.sk_foolery, 'xp': 0 },
            'persuasion': { 'level': obj.sk_persuasion, 'xp': 0 },
            'barter': { 'level': obj.sk_barter, 'xp': 0 },
            'performance': { 'level': obj.sk_performance, 'xp': 0 },
            'deception': { 'level': obj.sk_deceptionmagic, 'xp': 0 },
            'ritual': { 'level': obj.sk_ritualmagic, 'xp': 0 },
            'destruction': { 'level': obj.sk_destructionmagic, 'xp': 0 },
            'cooking': {'level':obj.sk_cooking, 'xp': 0},
            'foraging': {'level':obj.sk_foraging, 'xp': 0},
           
           }
       return JsonResponse(response_string)
    else:
        return JsonResponse({'status':'error'})

class UserProfileView(LoginRequiredMixin, DetailView): 
    model = User
    template_name = "user_detail.html"
    
    def get_object(self): 
        return self.request.user

WTTRPG/create/templates/create/character_form.html
{% extends "Header_and_Footer.html" %} 
{%block content%}

<body class="d-flex flex-column min-vh-100" style="background-color: #226150;">
<div class="container" style="background-color: #F9E49A;">
    <h4 class="text-center mb-2 text-decoration-underline">Quick Start Character Creator</h4>
    <p class="text-center mb-2 border-bottom border-dark">Major skills start at 25, minor at 15, the rest at 5<br />
    Str.= Movement<br />
    Agi.= Evasion chance<br />
    Gum.= Health<br />
    Int.= Awareness<br />
    Mys.= Spell slots<br />
    Per.= Prices & spell slots</p>
    <div class="text-center fw-bold">
        <form action="" method="post">
        {% csrf_token %}
        {{form.as_p}}
        <input class="mt-2 mb-2 justify-content-center btn text-white" style="background-color: #226150;" type="submit" value="Create">
        </form>
        </div>
    </div>
</body>

{% load static %}
<link rel="stylesheet" href="{% static 'create/character_form.css' %}">
<link rel="stylesheet" href="character_form.css">
<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>



<script>


    const globalPointBuys = new Map([
        
        ["30", 30],
        ["20", 20],
        ["16", 16],
        ["15", 15],
        ["10", 10],
        ["5",5]
    ]);

    function DeepCopyMap(existingMap) {
        const deepCopy = new Map(
            JSON.parse(
            JSON.stringify(Array.from(existingMap))
        ))
        return deepCopy
    }

    function PopulatePointbuys(elementID) {
        const selectElement = document.getElementById(elementID);
        jqID = "#" + elementID
        if ($(jqID + " option:selected").val() == "" ) {
            $(jqID).find('option:not(:first)').remove();
        }
        else {
            $(jqID).find('option:not(:selected)').remove();
        }
        pointbuys = DeepCopyMap(globalPointBuys)
        selectedBuys = CheckSelected()
        selectedBuys.forEach (function(buy) {
            if (buy != 0) {
                pointbuys.delete(buy)
            }
        })
        pointbuys.forEach (function(key, value) {
            let newOption = new Option(key, value);
            selectElement.appendChild(newOption);
         })
    };

    const attributesList = ["id_strength","id_agility","id_gumption","id_intelligence","id_mysticism","id_personality"]

    PopulatePointbuys("id_agility")
    PopulatePointbuys("id_gumption")
    PopulatePointbuys("id_strength")
    PopulatePointbuys("id_intelligence")
    PopulatePointbuys("id_mysticism")
    PopulatePointbuys("id_personality")

    function CheckSelected() {
        const selectedBuys = []
        attributesList.forEach (function(attribute) {
            attribute = "#" + attribute
            if ($(attribute).val() != "") {
                selectedBuys.push($(attribute).val())
            }
            else {
                selectedBuys.push(0)
            }
        })
        return selectedBuys
    }

    attributesList.forEach (function(attribute) {
        //add event listener to each attribute dropdown. should re-populate pointbuys on "change" for all attributes other than the one changing
        jqID = "#" + attribute
        $(jqID).change(function(){
            //update all other dropdowns with new list
            const filteredAttr = attributesList.filter(val=> val !== attribute)
            filteredAttr.forEach (function(attr) {
                PopulatePointbuys(attr)
            })
        })
    })


</script>


{% endblock content%}

WTTRPG/create/templates/create/character_list backup.html
{% extends "Header_and_Footer.html" %} 
{%block content%}
{% load static %}

<body style="background-color: #bf7e04;">
       <div class="container">
        <h2 class="pb-2 pt-3 border-bottom align-text-center">Characters</h2>
        <div class="container">
          <a href="#" class="nav-link">
          <h5 id="characterone" class="ps-1 pb-1 pt-3 mt-5 mb-4 border-top border-bottom border-start" style="background-color: #137a05;">Character one</h5>
          </a>
          <a href="#" class="nav-link">
          <h5 id="charactertwo" class="ps-1 pb-1 pt-3 mb-4 border-top border-bottom border-start" style="background-color: #137a05;">Character two</h5>
          </a>
          <a href="#" class="nav-link">
          <h5 id="characterthree" class="ps-1 pb-1 pt-3 mb-4 border-top border-bottom border-start" style="background-color: #137a05;">Character three</h5>
          </a>
        </div>
       </div>

{% endblock content%}

WTTRPG/create/templates/create/character_list.html
{% extends "Header_and_Footer.html" %} 
{%block content%}
{% load static %}

<body class="d-flex flex-column" style="background-color: #123524;">
       <div class="container d-flex flex-column min-vh-100" style="background-color: #fffbf1;">
        <h2 class="pb-2 border-bottom border-dark text-center mt-3">Characters</h2>
        <a href="{%url "create:qscc"%}" class="text-dark">
          <div class="d-flex flex-column text-center">
            <h4 class="ps-2 pb-1 mt-1 ms-5 me-5 mb-1 text-dark link-offset-2 link-offset-3-hover link-underline-opacity-0 link-secondary">Create a New Character</h4>
          </div>
      </a>
        <div class="container text-center justify-content-center align-items-center">
          {% for character in object_list %}
          <!-- href should link to character sheet. need to somehow access primary keys from object list to build the right URL -->
          
          <div class="row text-center mb-2 mt-3">
            <div class="col">
              <a href="{% url 'create:character_sheet' character.pk %}" class="card card-cover h-100 w-100 me-5 pt-2 overflow-hidden rounded-1 shadow" style="background-color: #262626fa;">
                <svg xmlns="http://www.w3.org/2000/svg" width="50" height="50" fill="white" class="bi bi-person-circle mx-auto" viewBox="0 0 16 16">
                  <path d="M11 6a3 3 0 1 1-6 0 3 3 0 0 1 6 0"/>
                  <path fill-rule="evenodd" d="M0 8a8 8 0 1 1 16 0A8 8 0 0 1 0 8m8-7a7 7 0 0 0-5.468 11.37C3.242 11.226 4.805 10 8 10s4.757 1.225 5.468 2.37A7 7 0 0 0 8 1"/>
                </svg>
                <p class="nav-link text-light">{{ character.name }}</p>
              </a>
            </div>
          </div>
          
          {% endfor %}
        </div>
       </div>

{% endblock content%}